os: linux

language: go

go: 
  - 1.14

services: 
  - postgresql
  - docker

script: 
  - go test -v ./...
   # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o gomux
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t christianst/gomux:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag christianst/gomux:latest christianst/gomux:$GIT_SHA
  - docker push christianst/gomux:latest
  - docker push christianst/gomux:$GIT_SHA